# -----------------------------------------------------------------------------
# TEST VARIANT (no modules): the network plus the three nginx containers that
# modules/web-app (x2) and modules/load-balancer used to create.
#
#   10.0.200.10  lb
#   10.0.200.11  blue
#   10.0.200.12  green
# -----------------------------------------------------------------------------

resource "network" "main" {
  subnet = "10.0.200.0/24"
}

# Was module "blue" (modules/web-app)
resource "container" "blue" {
  image {
    name = "nginx:1.27"
  }

  # Values flow from module inputs -> environment -> start-up script.
  environment = {
    APP_NAME    = "blue"
    APP_VERSION = variable.blue_version
    APP_COLOR   = "#2563eb"
  }

  # Write the site content from the environment, then run nginx in the
  # foreground so it stays PID 1 (learners can still run `nginx -s reload`).
  command = [
    "/bin/bash",
    "-c",
    <<-EOT
      set -e
      mkdir -p /usr/share/nginx/html
      cat > /usr/share/nginx/html/index.html <<HTML
      <!doctype html>
      <html lang="en">
        <head>
          <meta charset="utf-8">
          <title>$APP_NAME $APP_VERSION</title>
          <style>
            body { margin: 0; min-height: 100vh; display: grid; place-items: center;
                   background: $APP_COLOR; color: #fff; font-family: system-ui, sans-serif; }
            main { text-align: center; }
            h1   { font-size: 3rem; margin: 0 0 .5rem; text-transform: uppercase; letter-spacing: .1em; }
            p    { font-size: 1.25rem; margin: .25rem 0; opacity: .9; }
          </style>
        </head>
        <body>
          <main>
            <h1>$APP_NAME</h1>
            <p>version $APP_VERSION</p>
            <p>served by $(hostname)</p>
          </main>
        </body>
      </html>
      HTML
      echo "$APP_NAME $APP_VERSION" > /usr/share/nginx/html/version.txt
      exec nginx -g 'daemon off;'
    EOT
  ]

  port {
    local = 80
  }

  resources {
    cpu    = 250
    memory = 256
  }

  network {
    id         = resource.network.main.meta.id
    ip_address = "10.0.200.11"
    aliases    = ["blue"]
  }
}

# Was module "green" (modules/web-app)
resource "container" "green" {
  image {
    name = "nginx:1.27"
  }

  # Values flow from module inputs -> environment -> start-up script.
  environment = {
    APP_NAME    = "green"
    APP_VERSION = variable.green_version
    APP_COLOR   = "#16a34a"
  }

  # Write the site content from the environment, then run nginx in the
  # foreground so it stays PID 1 (learners can still run `nginx -s reload`).
  command = [
    "/bin/bash",
    "-c",
    <<-EOT
      set -e
      mkdir -p /usr/share/nginx/html
      cat > /usr/share/nginx/html/index.html <<HTML
      <!doctype html>
      <html lang="en">
        <head>
          <meta charset="utf-8">
          <title>$APP_NAME $APP_VERSION</title>
          <style>
            body { margin: 0; min-height: 100vh; display: grid; place-items: center;
                   background: $APP_COLOR; color: #fff; font-family: system-ui, sans-serif; }
            main { text-align: center; }
            h1   { font-size: 3rem; margin: 0 0 .5rem; text-transform: uppercase; letter-spacing: .1em; }
            p    { font-size: 1.25rem; margin: .25rem 0; opacity: .9; }
          </style>
        </head>
        <body>
          <main>
            <h1>$APP_NAME</h1>
            <p>version $APP_VERSION</p>
            <p>served by $(hostname)</p>
          </main>
        </body>
      </html>
      HTML
      echo "$APP_NAME $APP_VERSION" > /usr/share/nginx/html/version.txt
      exec nginx -g 'daemon off;'
    EOT
  ]

  port {
    local = 80
  }

  resources {
    cpu    = 250
    memory = 256
  }

  network {
    id         = resource.network.main.meta.id
    ip_address = "10.0.200.12"
    aliases    = ["green"]
  }
}

# Was module "lb" (modules/load-balancer). The backends map used to come from
# module.blue.output.address and module.green.output.address.
local "upstream_blocks" {
  value = join("\n", [for name, address in { blue = "10.0.200.11", green = "10.0.200.12" } : "upstream ${name} { server ${address}:80; }"])
}

resource "container" "lb" {
  image {
    name = "nginx:1.27"
  }

  environment = {
    LB_UPSTREAMS = local.upstream_blocks
    LB_ACTIVE    = variable.live_color
  }

  # The server block is written with a quoted heredoc so nginx variables such
  # as $host stay literal. __ACTIVE__ is then replaced with the live backend.
  command = [
    "/bin/bash",
    "-c",
    <<-EOT
      set -e
      CONF=/etc/nginx/conf.d/default.conf
      {
        echo "# Upstreams generated by the load-balancer module"
        printf '%s\n' "$LB_UPSTREAMS"
        cat <<'NGINX'

      server {
        listen 80;

        location / {
          # Change the upstream name below to switch traffic, then run:
          #   nginx -t && nginx -s reload
          proxy_pass http://__ACTIVE__;

          proxy_set_header Host $host;
          add_header X-Served-By $upstream_addr always;
        }

        location = /lb-health {
          default_type text/plain;
          return 200 "ok\n";
        }
      }
      NGINX
      } > "$CONF"
      sed -i "s/__ACTIVE__/$LB_ACTIVE/" "$CONF"
      exec nginx -g 'daemon off;'
    EOT
  ]

  port {
    local = 80
  }

  resources {
    cpu    = 250
    memory = 256
  }

  network {
    id         = resource.network.main.meta.id
    ip_address = "10.0.200.10"
    aliases    = ["lb"]
  }
}
