# -----------------------------------------------------------------------------
# load-balancer module: RESOURCES
#
# An nginx reverse proxy. It knows nothing about blue or green. It builds one
# upstream per entry in var.backends and sends traffic to var.active_backend.
# The lab wires the web-app module outputs into var.backends: that is module
# chaining.
# -----------------------------------------------------------------------------

# A local turns the backends map into nginx upstream blocks, one per line:
#   upstream blue { server 10.0.200.11:80; }
local "upstream_blocks" {
  value = join("\n", [for name, address in variable.backends : "upstream ${name} { server ${address}:80; }"])
}

resource "container" "lb" {
  image {
    name = "nginx:1.27"
  }

  environment = {
    LB_UPSTREAMS = local.upstream_blocks
    LB_ACTIVE    = variable.active_backend
  }

  # The server block is written with a quoted heredoc so nginx variables such
  # as $host stay literal. __ACTIVE__ is then replaced with the live backend.
  command = [
    "/bin/bash",
    "-c",
    <<-EOT
      set -e
      CONF=/etc/nginx/conf.d/default.conf
      {
        echo "# Upstreams generated by the load-balancer module"
        printf '%s\n' "$LB_UPSTREAMS"
        cat <<'NGINX'

      server {
        listen 80;

        location / {
          # Change the upstream name below to switch traffic, then run:
          #   nginx -t && nginx -s reload
          proxy_pass http://__ACTIVE__;

          proxy_set_header Host $host;
          add_header X-Served-By $upstream_addr always;
        }

        location = /lb-health {
          default_type text/plain;
          return 200 "ok\n";
        }
      }
      NGINX
      } > "$CONF"
      sed -i "s/__ACTIVE__/$LB_ACTIVE/" "$CONF"
      exec nginx -g 'daemon off;'
    EOT
  ]

  port {
    local = 80
  }

  resources {
    cpu    = 250
    memory = 256
  }

  network {
    id         = variable.network_id
    ip_address = variable.ip_address
    aliases    = ["lb"]
  }
}
